// THIS FILE WAS GENERATED BY `xtp-rust-bindgen`. DO NOT EDIT.

#![allow(non_snake_case)]
#![allow(unused_macros)]
use extism_pdk::*;

#[allow(unused)]
fn panic_if_key_missing() -> ! {
    panic!("missing key");
}

pub(crate) mod internal {
    pub(crate) fn return_error(e: extism_pdk::Error) -> i32 {
        let err = format!("{:?}", e);
        let mem = extism_pdk::Memory::from_bytes(&err).unwrap();
        unsafe {
            extism_pdk::extism::error_set(mem.offset());
        }
        -1
    }
}

#[allow(unused)]
macro_rules! try_input {
    () => {{
        let x = extism_pdk::input();
        match x {
            Ok(x) => x,
            Err(e) => return internal::return_error(e),
        }
    }};
}

#[allow(unused)]
macro_rules! try_input_json {
    () => {{
        let x = extism_pdk::input();
        match x {
            Ok(extism_pdk::Json(x)) => x,
            Err(e) => return internal::return_error(e),
        }
    }};
}

use base64_serde::base64_serde_type;

base64_serde_type!(Base64Standard, base64::engine::general_purpose::STANDARD);

mod exports {
    use super::*;

    #[no_mangle]
    pub extern "C" fn wave() -> i32 {
        let ret = crate::wave(try_input_json!()).and_then(extism_pdk::output);

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }
}

pub mod types {
    use super::*;

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct WaveArgs {
        /// frequency in hertz
        #[serde(rename = "freq_hz")]
        pub freq_hz: f32,

        /// an array of input numbers
        #[serde(rename = "inputs")]
        pub inputs: Vec<f32>,

        /// true if the left channel audio should be generated, false if right
        #[serde(rename = "isLeftChannel")]
        pub is_left_channel: bool,

        /// number between 0..1 representing the current phase
        #[serde(rename = "phase")]
        pub phase: f32,

        /// the raw sample number if you would like to compute the pitch and phase yourself
        #[serde(rename = "sample")]
        pub sample: i64,

        /// the raw sample rate if you would like to compute the pitch and phase yourself
        #[serde(rename = "sampleRate")]
        pub sample_rate: f32,
    }
}

mod raw_imports {
    use super::*;
    #[host_fn]
    extern "ExtismHost" {}
}
