# THIS FILE WAS GENERATED BY `xtp-python-bindgen`. DO NOT EDIT.

from typing import Optional, List  # noqa: F401
from datetime import datetime  # noqa: F401
import extism  # pyright: ignore
import plugin


from pdk_types import WaveArgs  # noqa: F401


# Imports


# Exports
# The implementations for these functions is in `plugin.py`


# User-defined function that computes a single sample of a waveform
@extism.plugin_fn
def wave():
    res = plugin.wave(extism.input(WaveArgs))
    extism.output(res)
