app_id = "app_01j66kjy8few8azm4bpdkwy6gz"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "plugin.wasm"
extension_point_id = "ext_01j9hn0bshfh2shvdxk9xz7zys"
name = "python_ring_mod"

[scripts]

  # xtp plugin build runs this script to generate the wasm file
  build = "uv sync && PYTHONPATH=./plugin:./.venv/lib/python3.13/site-packages extism-py -o plugin.wasm plugin/__init__.py"

  # xtp plugin init runs this script to format the plugin code
  format = "uv run ruff format plugin/*.py"

  # xtp plugin init runs this script before running the format script
  prepare = "bash prepare.sh && uv sync"
