app_id = "app_01j66kjy8few8azm4bpdkwy6gz"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "target/wasm32-unknown-unknown/release/plugin.wasm"
extension_point_id = "ext_01j9hn0bshfh2shvdxk9xz7zys"
name = "rust_voices"

[scripts]

# xtp plugin build runs this script to generate the wasm file
build = "cargo build --release --target wasm32-unknown-unknown"

# xtp plugin init runs this script to format the plugin code
format = "cargo fmt"

# xtp plugin init runs this script before running the format script
prepare = "bash prepare.sh"
