app_id = "app_01j66kjy8few8azm4bpdkwy6gz"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "dist/typescript_soft_clip.wasm"
extension_point_id = "ext_01j9hn0bshfh2shvdxk9xz7zys"
name = "typescript_soft_clip"

[scripts]

# xtp plugin build runs this script to generate the wasm file
build = "bash prepare.sh && npm run build"

# xtp plugin init runs this script to format the plugin code
format = "npm run format"

# xtp plugin init runs this script before running the format script
prepare = "bash prepare.sh"
