// THIS FILE WAS GENERATED BY `xtp-cpp-bindgen`. DO NOT EDIT.
#include <chrono>
#include <cstddef>
#include <expected>
#include <memory>
#include <span>
#include <stdint.h>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace pdk {

// Arguments to the user defined wave function
struct WaveArgs {
  // an array of input numbers
  std::vector<float> inputs;
  // the raw sample number if you would like to compute the pitch and phase
  // yourself
  int64_t sample;
  // frequency in hertz
  float freq_hz;
  // number between 0..1 representing the current phase
  float phase;
  // the raw sample rate if you would like to compute the pitch and phase
  // yourself
  float sampleRate;
  // true if the left channel audio should be generated, false if right
  bool isLeftChannel;
};

// host function errors
enum class Error { extism, host_null, not_json, json_null, not_implemented };

} // namespace pdk

namespace impl {

/**
 * User-defined function that computes a single sample of a waveform
 *
 * @param input
 * @return The computed sample
 */
std::expected<float, pdk::Error> wave(pdk::WaveArgs &&input);

} // namespace impl
