app_id = "app_01j66kjy8few8azm4bpdkwy6gz"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "dist/cpp_shockley_diode.wasm"
extension_point_id = "ext_01j9hn0bshfh2shvdxk9xz7zys"
name = "cpp_shockley_diode"

[scripts]

# xtp plugin build runs this script to generate the wasm file
build = "make -j4"

# xtp plugin init runs this script to format the plugin code
format = "make format"

# xtp plugin init runs this script before running the format script
prepare = "make wasisdk"
